#!/bin/bash

sudo nmcli con mod "Wired connection 1" ipv4.dns "9.9.9.9 149.112.112.112 192.168.21.1 192.168.21.2"
sudo nmcli con mod "Wired connection 1" ipv4.dns-search "campus.unice.fr iutnice.unice.fr iut.info.unice.fr unice.fr"
sudo nmcli con down "Wired connection 1"
sudo nmcli con up "Wired connection 1"

sudo systemctl enable systemd-resolved.service
sudo systemctl start systemd-resolved.service
