#!/bin/bash

echo "Installation VirtualBox"
sudo apt-get install -y dkms
if [[ ! -f "/etc/apt/sources.list.d/virtualbox.list" ]];then
  echo "deb http://download.virtualbox.org/virtualbox/debian buster contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list
fi
if ! dpkg-query -W -f='${Status}' dropbox  | grep "ok installed"
then
  wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  sudo apt update && sudo apt install -y virtualbox-6.1
  sudo usermod -aG vboxusers $USER
  vbextpack
fi
if [[ ! -f "/etc/bash_completion.d/VBoxManage" ]];then
  sudo wget https://raw.githubusercontent.com/gryf/vboxmanage-bash-completion/master/VBoxManage -O /etc/bash_completion.d/VBoxManage
fi
