#!/bin/bash

#https://www.how2shout.com/linux/install-teamviewer-on-debian-11-or-10-using-command-terminal/

if [[ ! -d /opt/teamviewer ]];then
  wget -q https://download.teamviewer.com/download/linux/teamviewer_amd64.tar.xz -O /tmp/teamviewer_amd64.tar.xz
  sudo tar xf /tmp/teamviewer_amd64.tar.xz -C /opt
  sudo chown -R ${USER} /opt/teamviewer*

  /opt/teamviewer/tv-setup checklibs #Vérifier les dépendances QT
  sudo apt-get install -y libdbus-1-3 libqt5gui5 libqt5widgets5 libqt5qml5 libqt5quick5 \
    libqt5webkit5 libqt5x11extras5 qml-module-qtquick2 qml-module-qtquick-controls \
    qml-module-qtquick-dialogs qml-module-qtquick-window2 qml-module-qtquick-layouts > /dev/null

  echo "exécuter une fois ./teamviewer pour valider que tout fonctionne avant de créer les fichiers de conf"
  /opt/teamviewer/teamviewer
  read
  sudo ln -s /opt/teamviewer/teamviewer.desktop /usr/share/applications/.
  sudo ln -s /opt/teamviewer/tv_bin/desktop/teamviewer_256.png /opt/teamviewer/tv_bin/desktop/teamviewer.png
fi
