#!/bin/bash

if ! dpkg-query -W -f='${Status}' google-chrome-stable > /dev/null
then
  echo "Installation Chrome"
  wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/chrome.deb
  sudo apt-get install -y /tmp/chrome.deb > /dev/null
fi

if ! dpkg-query -W -f='${Status}' torbrowser-launcher > /dev/null
then
  echo "Installation Tor"
  sudo apt-get install -y torbrowser-launcher  > /dev/null && torbrowser-launcher > /dev/null
fi
