#!/bin/bash

if [[ ! -d "/opt/BurpSuiteCommunity" && ! -d "${HOME}/BurpSuiteCommunity" ]]; then
  echo "Installation BurpSuite"
  wget -q "https://portswigger.net/burp/releases/download?product=community&type=Linux" -O /tmp/burp.sh
  sh /tmp/burp.sh > /dev/null
  sudo chown root:root ${HOME}/BurpSuiteCommunity/burpbrowser/*/chrome-sandbox
  sudo chmod u+s ${HOME}/BurpSuiteCommunity/burpbrowser/*/chrome-sandbox
fi
