#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

source ~/.bash_functions

url=`github_get_latest_dwds wez/wezterm | fzf`
wget -q ${url} -O /tmp/wezterm.deb

echo "Installation Wezterm"
sudo apt-get install -y /tmp/wezterm.deb > /dev/null
