#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

echo "Installation Wezterm"
wget https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly.Debian11.deb -O /tmp/wezterm.deb
sudo apt-get install -y /tmp/wezterm.deb > /dev/null
