#!/bin/bash

VBPKG='virtualbox-6.1'

if [[ ! -f "/etc/apt/sources.list.d/virtualbox.list" ]];then
  CODENAME=`lsb_release -sc`
  echo "deb http://download.virtualbox.org/virtualbox/debian ${CODENAME} contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list
fi
if ! dpkg-query -W -f='${Status}' ${VBPKG} > /dev/null
then
  echo "Installation VirtualBox"
  wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  sudo apt-get update > /dev/null && sudo apt-get install -y ${VBPKG} > /dev/null
  sudo usermod -aG vboxusers $USER
  vbextpack
  [[ ! -f "/etc/bash_completion.d/VBoxManage" ]] && \
    sudo wget -q https://raw.githubusercontent.com/gryf/vboxmanage-bash-completion/master/VBoxManage -O /etc/bash_completion.d/VBoxManage
fi
