#!/bin/bash

echo "Installation Teams"
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
if [[ ! -f "/etc/apt/sources.list.d/teams.list" ]]; then
  sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main" > /etc/apt/sources.list.d/teams.list'
  sudo apt update
fi
sudo apt install -y teams
[[ -f ${HOME}/.config/autostart/teams.desktop ]] && rm {HOME}/.config/autostart/teams.desktop
