#!/bin/bash

echo "Installation depo multimedia"
if ! dpkg-query -W -f='${Status}' deb-multimedia-keyring  | grep "ok installed"
then
  wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
  sudo dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
  sudo apt update && sudo apt upgrade -y
fi
if [[ ! -f "/etc/apt/sources.list.d/deb-multimedia.list" ]]; then
  echo "deb http://www.deb-multimedia.org buster main non-free" | sudo tee -a /etc/apt/sources.list.d/deb-multimedia.list
  echo "deb http://www.deb-multimedia.org buster-backports main" | sudo tee -a /etc/apt/sources.list.d/deb-multimedia.list
  sudo apt update && sudo apt upgrade -y
fi

echo "Installation Multimedia"
sudo apt install -y vlc vlc-plugin-base libnfs13 handbrake* libdvdnav4 libdvd-pkg libdvdread4
sudo dpkg-reconfigure libdvd-pkg
