#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

echo "Installation Multimedia"
sudo apt-get install -y vlc vlc-plugin-base libnfs13 handbrake* libdvdnav4 libdvd-pkg libdvdread8 libdvd-pkg mpv guvcview v4l2loopback-dkms v4l-utils
sudo dpkg-reconfigure libdvd-pkg
