#!/bin/bash

install_browsers

install_burpsuite

PKGS="ssh-askpass-gnome xclip keychain icedtea-netx network-manager-pptp-gnome \
  libcanberra-gtk-module calibre libreoffice flameshot copyq rdesktop lightdm-remote-session-freerdp2 \
  remmina-plugin-nx remmina-common remmina-plugin-exec remmina-plugin-xdmcp \
  remmina-plugin-spice remmina-plugin-rdp remmina-plugin-secret remmina-plugin-vnc remmina \
  nautilus-extension-burner nautilus-filename-repairer nautilus-scripts-manager"

echo "Installation apt-get ${PKGS}"
sudo apt-get -y install ${PKGS} > /dev/null

echo "Ajout shorcut flameshot"
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot '[]'
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ name 'PrtScr flameshot'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ command '/usr/bin/flameshot gui'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ binding 'Print'
