#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

sudo apt-get install -y build-essential curl git jq linux-headers-amd64 >/dev/null
git config --global pull.ff only

echo "PATH dirs"
mkdir -p "$HOME"/bin "$HOME"/.local/bin

echo "Desactivation accès root"
sudo passwd -l root >/dev/null

echo "désactivation maj cache man-db"
sudo apt-get -y remove --auto-remove man-db >/dev/null
sudo systemctl mask man-db.service
sudo systemctl daemon-reload

echo "désactivation veille automatique"
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

echo "Installation nushell"
NUVER=$(curl --silent "https://api.github.com/repos/nushell/nushell/releases/latest" | jq -r '.tag_name')
echo $NUVER
wget https://github.com/nushell/nushell/releases/download/$NUVER/nu-$NUVER-x86_64-unknown-linux-gnu.tar.gz -O /tmp/nu.tgz
sudo tar xzf /tmp/nu.tgz -C /usr/local/bin/ nu
