#!/bin/bash

install_browsers

install_burpsuite

PKGS="sudo ssh-askpass-gnome xclip keychain icedtea-netx network-manager-pptp-gnome \
  libcanberra-gtk-module calibre libreoffice \
  remmina-plugin-nx remmina-plugin-telepathy remmina-common \
  remmina-plugin-exec remmina-plugin-xdmcp \
  remmina-plugin-spice remmina-plugin-rdp remmina-plugin-secret remmina-plugin-vnc remmina \
  nautilus-extension-burner nautilus-filename-repairer nautilus-scripts-manager"

sudo apt -y install ${PKGS}

PKGS="flameshot"
sudo apt -y install -t buster-backports ${PKGS}
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot '[]'
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ name 'PrtScr flameshot'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ command '/usr/bin/flameshot gui'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ binding 'Print'
