#!/bin/bash

if [[ ! $# -eq 5 ]]; then
  echo "Erreur:  donnez en paramètre la vm de test, l'iso, le fichier preseed et le menu installer de isolinux et grub, ie:"
  echo "Exemple:  preseed_test firmware-10.8.0-amd64-netinst.iso preseed.cfg isolinux.cfg grub.cfg"
  exit 1
fi

VM=$1
INPUT=$2
PRESEED=$3
ISOLINUX=$4
GRUB=$5
OUTPUT="/tmp/debian-nonofficial-preseed.iso"

vboxmanage controlvm ${VM} poweroff
vboxmanage storageattach ${VM} --storagectl IDE --port 1 --device 0 --type dvddrive --medium "emptydrive"
sudo rm -f ${OUTPUT}

preseed_create ${INPUT} ${PRESEED} ${ISOLINUX} ${GRUB} || exit

vboxmanage storageattach ${VM} --storagectl IDE --port 1 --device 0 --type dvddrive --medium ${OUTPUT} && vboxmanage startvm ${VM}
