#!/bin/bash

if [[ ! $# -eq 2 ]]; then
  echo "Erreur:  donnez l'ancien et le nouveau login, ie:"
  echo "Exemple:  renameuser old new"
  exit 1
fi
OLD=$1
NEW=$2

sudo usermod -l ${NEW} ${OLD}
sudo usermod -d /home/${NEW} -m ${NEW}
sudo groupmod -n ${NEW} ${OLD}
id ${NEW}
