#!/bin/bash

echo "Installation plugin nvim"
if [[ ! -f "${HOME}/.local/share/nvim/site/autoload/plug.vim" ]]; then
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
    --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      nvim --headless +PlugUpgrade +qall
    else
      nvim --headless +PlugUpgrade +qall
      nvim --headless +PlugUpdate +qall
fi
