#!/bin/bash

if [[ ! -f "${HOME}/.local/share/nvim/site/autoload/plug.vim" ]]; then
  echo "Installation plugin nvim"
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
    --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' > /dev/null
      nvim --headless +PlugUpgrade +qall > /dev/null
    else
      nvim --headless +PlugUpgrade +qall > /dev/null
      nvim --headless +PlugUpdate +qall > /dev/null
fi
